name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일 로드
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/insta-server/tobe

      - name: SSH로 EC2에 접속
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: | 
            rm -rf /home/ubuntu/insta-server/current
            mkdir /home/ubuntu/insta-server/current
            mv /home/ubuntu/insta-server/tobe/project.jar /home/ubuntu/insta-server/current/project.jar
            cd /home/ubuntu/insta-server/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > output.log 2>&1 &
            rm -rf /home/ubuntu/insta-server/tobe

#      - name: SSH로 EC2에 접속
#        uses: appleboy/ssh-action@v1.2.2
#        env:
#          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          envs: APPLICATION_PROPERTIES
#          script_stop: true
#          script: |
#            cd /home/ubuntu/insta-sever
#            rm -rf src/main/resources/application.yml
#            git pull origin main
#            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
#            ./gradlew clean build
#            sudo fuser -k -n tcp 8080 || true
#            nohup java -jar build/libs/*SNAPSHOT.jar > output.log 2>&1 &